name: 🚀 Feature Request
description: Request a new feature or enhancement aligned with the project roadmap
title: "[Feature]: "
labels: ["enhancement", "roadmap"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to request a feature! Please check our [Product Roadmap](https://github.com/m-idriss/converter/blob/master/ROADMAP.md) to see if your feature is already planned.

  - type: dropdown
    id: roadmap-phase
    attributes:
      label: Roadmap Phase Alignment
      description: Which phase of our roadmap does this feature align with?
      options:
        - "Phase 1: Core Improvements (P1 - High Priority)"
        - "Phase 2: Feature Expansion (P1-P2 - High-Medium Priority)"
        - "Phase 3: Advanced Features (P2 - Medium Priority)"
        - "Phase 4: Innovation & Scale (P2-P3 - Medium-Low Priority)"
        - "New feature not in current roadmap"
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What category does this feature belong to?
      options:
        - "Performance Optimization"
        - "Accessibility & UX"
        - "Core Functionality Enhancements"
        - "File Format Support"
        - "Calendar Integration"
        - "Smart Features / AI"
        - "Collaboration & Sharing"
        - "Enterprise Features"
        - "Mobile Enhancement"
        - "Analytics & Insights"
        - "Other"
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: How would you classify the priority of this feature?
      options:
        - "P1 (High): Critical for user experience and performance"
        - "P2 (Medium): Important for feature completeness and scalability"
        - "P3 (Low): Nice-to-have improvements and future innovations"
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What user need does it address?
      placeholder: "As a user, I need... because..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the feature you'd like to see implemented
      placeholder: "I would like the application to..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: What alternatives have you considered?
      placeholder: "Other approaches could include..."

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: What are the specific requirements for this feature to be considered complete?
      placeholder: |
        - [ ] Feature does X
        - [ ] Feature handles Y case
        - [ ] Performance impact is minimal
        - [ ] Tests are included

  - type: dropdown
    id: user-type
    attributes:
      label: Target Users
      description: Who would benefit from this feature?
      multiple: true
      options:
        - "Individual users (personal use)"
        - "Small teams (collaboration)"
        - "Enterprise users (business use)"
        - "Developers (API/integration)"
        - "Accessibility users"
        - "Mobile users"

  - type: checkboxes
    id: impact
    attributes:
      label: Expected Impact
      description: What areas would this feature impact? (Select all that apply)
      options:
        - label: "User Experience (UX)"
        - label: "Performance"
        - label: "Accessibility"
        - label: "Security"
        - label: "Scalability"
        - label: "Maintenance"

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, mockups, or examples about the feature request