name: Quick Issue
description: Minimal issue template
title: "[Issue]"
labels: []
body:
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: "Briefly describe the issue or request."
      placeholder: "Describe the issue here..."